"""add preferred_notification_method

Revision ID: 28df309c135a
Revises: 9020710bf715
Create Date: 2026-06-12 23:59:52.937018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '28df309c135a'
down_revision: Union[str, Sequence[str], None] = '9020710bf715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_notification_method', sa.String(), nullable=True, server_default='auto'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_notification_method')
    # ### end Alembic commands ###
