"""Add creator_name and marketplace fields to Course

Revision ID: 80ad7202a2c3
Revises: 28df309c135a
Create Date: 2026-06-16 07:12:29.521878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '80ad7202a2c3'
down_revision: Union[str, Sequence[str], None] = '28df309c135a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_ai_lessons')
    with op.batch_alter_table('onboarding_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onboarding_metrics_user_rid'))

    op.drop_table('onboarding_metrics')
    with op.batch_alter_table('ai_lessons', schema=None) as batch_op:
        batch_op.alter_column('curriculum_metadata',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('module_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_ai_lessons_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_lessons_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_lessons_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_lessons_parent_id'), ['parent_id'], unique=False)

    with op.batch_alter_table('ai_performance_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_ai_performance_logs_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_performance_logs_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_performance_logs_user_rid'), ['user_rid'], unique=False)

    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('grade_percentage',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('code_generation_sessions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('session_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('course_progress', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('video_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('approval_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('approval_remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('module_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_lesson_progress_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_progress_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_progress_user_rid'), ['user_rid'], unique=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('subject_roadmaps', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_subject_roadmaps_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_subject_roadmaps_user_rid'), ['user_rid'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('code_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_transactions_payment_reference'), ['payment_reference'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'USER'"))
        batch_op.alter_column('momo_provider',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('momo_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('momo_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('preferred_payment_method',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'mobile_money'"))
        batch_op.alter_column('paystack_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('paypal_email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('stripe_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('payout_method',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'mobile_money'"))
        batch_op.alter_column('payout_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('payout_provider',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('payout_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('learning_goal',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'General Exploration'"))
        batch_op.alter_column('preferred_style',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'Balanced'"))

    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('preferred_style',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Balanced'"))
        batch_op.alter_column('learning_goal',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'General Exploration'"))
        batch_op.alter_column('payout_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('payout_provider',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('payout_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('payout_method',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'mobile_money'"))
        batch_op.alter_column('stripe_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('paypal_email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('paystack_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('preferred_payment_method',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'mobile_money'"))
        batch_op.alter_column('momo_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('momo_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('momo_provider',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'USER'"))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_payment_reference'))
        batch_op.alter_column('code_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('subject_roadmaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_roadmaps_user_rid'))
        batch_op.drop_index(batch_op.f('ix_subject_roadmaps_subject'))
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.CHAR(length=32),
               nullable=True)

    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_index(batch_op.f('ix_lesson_progress_user_rid'))
        batch_op.drop_index(batch_op.f('ix_lesson_progress_module_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_progress_lesson_id'))
        batch_op.alter_column('module_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.CHAR(length=32),
               nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('approval_remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('approval_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('course_progress', schema=None) as batch_op:
        batch_op.alter_column('video_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('course_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('code_generation_sessions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('grade_percentage',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('ai_performance_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_performance_logs_user_rid'))
        batch_op.drop_index(batch_op.f('ix_ai_performance_logs_topic'))
        batch_op.drop_index(batch_op.f('ix_ai_performance_logs_subject'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               nullable=True)

    with op.batch_alter_table('ai_lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_lessons_parent_id'))
        batch_op.drop_index(batch_op.f('ix_ai_lessons_module_id'))
        batch_op.drop_index(batch_op.f('ix_ai_lessons_is_verified'))
        batch_op.drop_index(batch_op.f('ix_ai_lessons_is_public'))
        batch_op.alter_column('module_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('curriculum_metadata',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'"))

    op.create_table('onboarding_metrics',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('user_rid', sa.VARCHAR(), nullable=True),
    sa.Column('step_reached', sa.INTEGER(), nullable=True),
    sa.Column('action_taken', sa.VARCHAR(), nullable=True),
    sa.Column('time_spent_ms', sa.INTEGER(), nullable=True),
    sa.Column('first_correct_answer_rate', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('time_to_first_lesson_ms', sa.INTEGER(), nullable=True),
    sa.Column('device_type', sa.VARCHAR(), nullable=True),
    sa.Column('onboarding_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('session_metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onboarding_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_metrics_user_rid'), ['user_rid'], unique=False)

    op.create_table('_alembic_tmp_ai_lessons',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('creator_rid', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('topic', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('difficulty', sa.VARCHAR(), nullable=True),
    sa.Column('style', sa.VARCHAR(), nullable=True),
    sa.Column('objectives', sqlite.JSON(), nullable=True),
    sa.Column('scenes', sqlite.JSON(), nullable=True),
    sa.Column('target_duration_minutes', sa.INTEGER(), nullable=True),
    sa.Column('total_scenes', sa.INTEGER(), nullable=True),
    sa.Column('completed_scenes', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_partially_generated', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('last_successful_scene_index', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('curriculum_metadata', sqlite.JSON(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('module_id', sa.VARCHAR(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.Column('parent_id', sa.VARCHAR(), nullable=True),
    sa.Column('usage_count', sa.INTEGER(), nullable=True),
    sa.Column('popularity_score', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
