import uuid
from datetime import datetime
from sqlalchemy import Column, String, Integer, Numeric, DateTime, JSON, Boolean, Text, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from common.database.db_session import Base

class AICourse(Base):
    """
    AI-Generated dynamic courses.
    These are tailored to a specific user and goal.
    """
    __tablename__ = "ai_courses"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_rid = Column(String, index=True, nullable=False)
    
    title = Column(String, nullable=False)
    skill_level = Column(String, default="Beginner")
    teacher_type = Column(String) # AI Math Teacher, AI Python Teacher, etc.
    
    roadmap_data = Column(JSON, nullable=True) # Full structure of the course
    season_id = Column(Integer, index=True)
    
    is_completed = Column(Boolean, default=False)
    final_grade = Column(Numeric(5, 2), nullable=True) # Percentage
    
    certificate_id = Column(String, unique=True, nullable=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)

class AITopic(Base):
    """
    Individual learning topics generated by the AI Teacher.
    """
    __tablename__ = "ai_topics"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    course_id = Column(String, ForeignKey("ai_courses.id"), index=True)
    
    title = Column(String, nullable=False)
    explanation = Column(Text, nullable=True)
    
    # Store links to YouTube, Articles, Documentation
    resources = Column(JSON, nullable=True) 
    
    # AI Assignment attached to this topic
    assignment_id = Column(String, index=True, nullable=True)
    
    is_completed = Column(Boolean, default=False)
    position = Column(Integer, default=0)

class AIAssignment(Base):
    """
    AI-generated assignments and grading history.
    """
    __tablename__ = "ai_assignments"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    topic_id = Column(String, index=True)
    user_rid = Column(String, index=True)
    
    questions = Column(JSON)
    user_answers = Column(JSON, nullable=True)
    
    ai_feedback = Column(Text, nullable=True)
    score = Column(Numeric(5, 2), nullable=True)
    
    submitted_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

class ContinuityTransfer(Base):
    """
    Audit log of course transfers from one season to another.
    """
    __tablename__ = "continuity_transfers"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_rid = Column(String, index=True)
    
    old_product_code = Column(String)
    new_product_code = Column(String)
    
    course_id = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)

class AICompanionSession(Base):
    """
    Stores a long-term conversation session between a student and their AI Companion.
    """
    __tablename__ = "ai_companion_sessions"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_rid = Column(String, index=True)
    
    # Context summary of what the student is currently struggling with
    context_summary = Column(String, nullable=True)
    
    # Full history or serialized buffer of recent messages
    message_history = Column(JSON, default=list) 
    
    last_active = Column(DateTime, default=datetime.utcnow)
